In [1]:
import pandas as pd

In [3]:
data = {
    'Empresa': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'Nome': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Venda': [200, 120, 340, 124, 243, 350]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [ ]:
group =df.groupby('Empresa')
# agrupa pelo indice Empresa, como tem 2 de cada entao tera 3 nomes de empresa

In [8]:
group

In [ ]:
group.sum()
# soma Venda por grupo

               Nome  Venda
Empresa
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [ ]:
group =df.groupby('Nome')
# agrupa por nome

In [ ]:
group.sum().loc['Amy']
# soma as vendas e localza a Amy

Empresa    MSFT
Venda       340
Name: Amy, dtype: object